spring:
  application:
    name: homepage-feign

server:
  port: 8200

eureka:
  client:
    service-url:
      #将自己注册进下面这个地址的服务注册中心
      defaultZone: http://admin:admin@localhost:8000/eureka/

feign:
  #默认是不支持的
  hystrix:
    enabled: true
  #修改调用超时时间（默认是1秒就算超时）
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
